config/routes.rb
Rails.application.routes.draw do
  resources :request_transaction_funding_sources

  resources :modal_reports

  resources :request_programs

  resources :funding_sources

  resources :admin_cards

  resources :funding_source_allocations

  resources :sub_initiatives

  resources :sub_programs

  resources :request_funding_sources
  resources :request_evaluation_metrics
  resources :request_transactions
  resources :grant_requests
  resources :fip_requests
  resources :request_letters
  resources :request_users
  resources :granted_requests
  resources :request_organizations
  resources :programs
  resources :initiatives
  resources :request_reports
  resources :project_requests
  resources :outside_grants
  resources :grantee_portal

end

app/models/fip_request.rb
class FipRequest < Request
  include FluxxFipRequest
end

app/models/funding_source.rb
class FundingSource < ActiveRecord::Base
  include FluxxFundingSource
end

app/models/grant_request.rb
class GrantRequest < Request
  include FluxxGrantRequest
end

app/models/initiative.rb
class Initiative < ActiveRecord::Base
  include FluxxInitiative
end

app/models/liquid_filters.rb
module LiquidFilters
  include ActionView::Helpers::NumberHelper
  include ActionView::Helpers::TextHelper
  include ApplicationGrantHelper
  
  def format_date(date, format = 'full')
    return nil unless date
    date.send(format)
  end
  
  # ex: {{ request_transaction.amount_due | currency: 'Rs. ' }}
  def currency(number, unit='$', delimiter=',', precision=0, format='%u%n')
    return '' if number.blank? || number == 0
    number_to_currency(number, :unit => unit, :delimiter => delimiter, :precision => precision, :format => format)
  end
  
  def titlecase(string)
    return nil unless string
    string.titlecase
  end
  
  def capitalize(string)
    return nil unless string
    string.capitalize
  end
  
  def to_english(num)
    return nil unless num
    num.to_english
  end
  
  # provides the ability to assign a value from the result of a filter
  # ex: {{ request.request_reports | sort: 'due_at' | assign_to: 'request_reports' }}
  def assign_to(value, name)
    @context[name] = value ; nil
  end
  
  def to_rtf(string)
    # http://en.wikipedia.org/wiki/Rich_Text_Format#Character_encoding
    # RTF is an 8-bit format. That would limit it to ASCII, but RTF can encode characters beyond ASCII by escape sequences.
    # For a Unicode escape the control word \u is used, followed by a 16-bit signed decimal integer giving the Unicode code point number.
    # ... Until RTF specification version 1.5 release in 1997, RTF has only handled 7-bit characters directly and 8-bit characters encoded as hexadecimal (using \'xx).
    # ... RTF files are usually 7-bit ASCII plain text.
    return nil unless string
    string.gsub!("\n", "\\line\n")
    string.gsub!("\t", "\\tab\t")
    
    # unicode rtf output to covert non-ascii chars: 8-bit to hex, 16-bit to code point
    string.unpack('U*').map { |n| n < 128 ? n.chr : n < 256 ? "\\'#{n.to_s(16)}" : "\\u#{n}\\'3f" }.join('')
  end
  
  def with_line_break(string)
    string.present? ? "#{string}<br/>" : string
  end
  
  def date_add_months(time, number_months=0)
    time + number_months.to_i.months
  end
  
end

Liquid::Template.register_filter(LiquidFilters)

app/models/organization.rb
class Organization < ActiveRecord::Base
  include FluxxGrantOrganization
end

app/models/program.rb
class Program < ActiveRecord::Base
  include FluxxProgram
end

app/models/project.rb
class Project < ActiveRecord::Base
  include FluxxGrantProject
end

app/models/project_request.rb
class ProjectRequest < ActiveRecord::Base
  include FluxxProjectRequest
end

app/models/request.rb
class Request < ActiveRecord::Base
  include FluxxRequest
end

app/models/request_geo_state.rb
class RequestGeoState < ActiveRecord::Base
  include FluxxRequestGeoState
end

app/models/request_program.rb
class RequestProgram < ActiveRecord::Base
  include FluxxRequestProgram
end

app/models/request_report.rb
class RequestReport < ActiveRecord::Base
  include FluxxRequestReport
end

app/models/request_user.rb
class RequestUser < ActiveRecord::Base
  include FluxxRequestUser
end

app/models/role.rb
class Role < ActiveRecord::Base
  include FluxxRole
  add_roleable_type 'Program', Program.name
end

app/models/role_user.rb
class RoleUser < ActiveRecord::Base
  include FluxxGrantRoleUser
end

app/models/sub_initiative.rb
class SubInitiative < ActiveRecord::Base
  include FluxxSubInitiative
end

app/models/sub_program.rb
class SubProgram < ActiveRecord::Base
  include FluxxSubProgram
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
  validates_confirmation_of :password
  acts_as_authentic do |c|
    # c.my_config_option = my_value # for available options see documentation in: Authlogic::ActsAsAuthentic
    c.act_like_restful_authentication = true
    c.validate_login_field=false
    c.validate_password_field=false
    c.validate_email_field=false
  end # block optional
  
  include ::FluxxGrantUser
  
  
  # TODO: Make it so that authlogic does not reindex delta indexing in sphinx upon signin
  
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  private
  # NOTE ESH: Copied this method straight from authlogic's lib/authlogic/session/cookies.rb
  #           to force it to send the user_credentials cookie back with EVERY request.  This is an effort to prevent the session cookie
  #           or user_credentials cookie from being dropped
  # Tries to validate the session from information in the cookie
  def persist_by_cookie
    persistence_token, record_id = cookie_credentials
    if !persistence_token.nil?
      self.record = record_id.nil? ? search_for_record("find_by_persistence_token", persistence_token) : search_for_record("find_by_#{klass.primary_key}", record_id)
      self.unauthorized_record = record if record && record.persistence_token == persistence_token
      retval = valid?
      # Force the cookie to be sent back to the browser each time so it can be regained if it gets dropped
      save_cookie if retval && self.record
      retval
    else
      false
    end
  end
end

app/models/workflow_event.rb
class WorkflowEvent < ActiveRecord::Base
  include FluxxGrantWorkflowEvent
end

app/controllers/initiatives_controller.rb
class InitiativesController < ApplicationController
  include FluxxInitiativesController
end

app/views/initiatives/_initiative_filter.html.haml
- unless FLUXX_CONFIGURATION[:hide_program]
  = form.input :program_id, :label => I18n.t(:program_name), :as => :select, :required => false, :collection => Program.load_all_nonrollup.sort_by{|prog| prog.name || ''}.map {|prog|[prog.name, prog.id]}, :input_html => {:class => 'add-another'}
- unless FLUXX_CONFIGURATION[:hide_sub_program]
  = form.input :sub_program_id, :label => I18n.t(:sub_program_name), :as => :select, :required => false, :collection => SubProgram.load_all.sort_by{|prog| prog.name || ''}.map {|prog|[prog.name, prog.id]}, :input_html => {:class => 'add-another'}
= form.input :not_retired, :as => :boolean, :label => "Exclude Retired #{(I18n.t(:initiative_name)).pluralize}"

app/views/initiatives/_initiative_form.html.haml
- sub_programs = (form.object.program.load_sub_programs if form.object.program) || []
= form.input :name, :label => "Name"
- unless FLUXX_CONFIGURATION[:hide_program]
  = form.input :program_id, :label => I18n.t(:program_name), :as => :select, :collection => Program.load_all_nonrollup.map{|program| [program.description || program.name, program.id]}, :input_html => {:class => 'program-dropdown-select', 'data-related-child-param' => 'program_id', 'data-related-child' => ".sub-program-select"}
- unless FLUXX_CONFIGURATION[:hide_sub_program]
  = form.input :sub_program_id, :label => I18n.t(:sub_program_name), :as => :select, :collection => sub_programs.map{|sub_program| [sub_program.description || sub_program.name, sub_program.id]}, :input_html => {:class => 'sub-program-select', 'data-related-child-param' => 'sub_program_id', 'data-param'.to_sym => 'program_id', 'data-src'.to_sym => sub_programs_path(:format => 'autocomplete')}
= form.input :retired, :as => :boolean, :label => "Retired:"

= form.commit_button

app/views/initiatives/_initiative_list.html.haml
- spending_year = Time.now.year
%h2= model.name
%h4
  = model.sub_program.program.name if model.sub_program && model.sub_program.program
  |
  = model.sub_program.name if model.sub_program
%h4 
  = model.total_allocation(:spending_year => spending_year).to_currency
  Current Year Funding

app/views/initiatives/_initiative_show.html.haml
%h1= model.name

.pairs
  .key= "Program"
  .value= model.program.name if model.program

.pairs
  .key= "Sub-Program"
  .value= model.sub_program.name if model.sub_program

- current_year = Time.now.year
- year_range = ((current_year-25)..(current_year + 2))
= semantic_form_for FundingSourceAllocation.new(:spending_year => current_year), :html => {:class => ''} do |form|
  = form.input :spending_year, :label => "Spending Year", :as => :select, :collection => year_range.to_a.reverse, :input_html => {"data-target".to_sym => ".funding-source-allocations-partial-span", :class => "refresh-partial"}

= render :partial => 'funding_source_allocations/list_funding_source_allocations', :locals => {:models => (model.funding_source_allocations(:spending_year => current_year)), :initiative_id => model.id, :program_attributes => {:spending_year => current_year, :initiative_id => model.id}}