config/routes.rb
Rails.application.routes.draw do
  resources :request_transaction_funding_sources

  resources :modal_reports

  resources :request_programs

  resources :funding_sources

  resources :admin_cards

  resources :funding_source_allocations

  resources :sub_initiatives

  resources :sub_programs

  resources :request_funding_sources
  resources :request_evaluation_metrics
  resources :request_transactions
  resources :grant_requests
  resources :fip_requests
  resources :request_letters
  resources :request_users
  resources :granted_requests
  resources :request_organizations
  resources :programs
  resources :initiatives
  resources :request_reports
  resources :project_requests
  resources :outside_grants
  resources :grantee_portal

end

app/models/fip_request.rb
class FipRequest < Request
  include FluxxFipRequest
end

app/models/funding_source.rb
class FundingSource < ActiveRecord::Base
  include FluxxFundingSource
end

app/models/grant_request.rb
class GrantRequest < Request
  include FluxxGrantRequest
end

app/models/initiative.rb
class Initiative < ActiveRecord::Base
  include FluxxInitiative
end

app/models/liquid_filters.rb
module LiquidFilters
  include ActionView::Helpers::NumberHelper
  include ActionView::Helpers::TextHelper
  include ApplicationGrantHelper
  
  def format_date(date, format = 'full')
    return nil unless date
    date.send(format)
  end
  
  # ex: {{ request_transaction.amount_due | currency: 'Rs. ' }}
  def currency(number, unit='$', delimiter=',', precision=0, format='%u%n')
    return '' if number.blank? || number == 0
    number_to_currency(number, :unit => unit, :delimiter => delimiter, :precision => precision, :format => format)
  end
  
  def titlecase(string)
    return nil unless string
    string.titlecase
  end
  
  def capitalize(string)
    return nil unless string
    string.capitalize
  end
  
  def to_english(num)
    return nil unless num
    num.to_english
  end
  
  # provides the ability to assign a value from the result of a filter
  # ex: {{ request.request_reports | sort: 'due_at' | assign_to: 'request_reports' }}
  def assign_to(value, name)
    @context[name] = value ; nil
  end
  
  def to_rtf(string)
    # http://en.wikipedia.org/wiki/Rich_Text_Format#Character_encoding
    # RTF is an 8-bit format. That would limit it to ASCII, but RTF can encode characters beyond ASCII by escape sequences.
    # For a Unicode escape the control word \u is used, followed by a 16-bit signed decimal integer giving the Unicode code point number.
    # ... Until RTF specification version 1.5 release in 1997, RTF has only handled 7-bit characters directly and 8-bit characters encoded as hexadecimal (using \'xx).
    # ... RTF files are usually 7-bit ASCII plain text.
    return nil unless string
    string.gsub!("\n", "\\line\n")
    string.gsub!("\t", "\\tab\t")
    
    # unicode rtf output to covert non-ascii chars: 8-bit to hex, 16-bit to code point
    string.unpack('U*').map { |n| n < 128 ? n.chr : n < 256 ? "\\'#{n.to_s(16)}" : "\\u#{n}\\'3f" }.join('')
  end
  
  def with_line_break(string)
    string.present? ? "#{string}<br/>" : string
  end
  
  def date_add_months(time, number_months=0)
    time + number_months.to_i.months
  end
  
end

Liquid::Template.register_filter(LiquidFilters)

app/models/organization.rb
class Organization < ActiveRecord::Base
  include FluxxGrantOrganization
end

app/models/program.rb
class Program < ActiveRecord::Base
  include FluxxProgram
end

app/models/project.rb
class Project < ActiveRecord::Base
  include FluxxGrantProject
end

app/models/project_request.rb
class ProjectRequest < ActiveRecord::Base
  include FluxxProjectRequest
end

app/models/request.rb
class Request < ActiveRecord::Base
  include FluxxRequest
end

app/models/request_program.rb
class RequestProgram < ActiveRecord::Base
  include FluxxRequestProgram
end

app/models/request_report.rb
class RequestReport < ActiveRecord::Base
  include FluxxRequestReport
end

app/models/request_user.rb
class RequestUser < ActiveRecord::Base
  include FluxxRequestUser
end

app/models/role.rb
class Role < ActiveRecord::Base
  include FluxxRole
  add_roleable_type 'Program', Program.name
end

app/models/role_user.rb
class RoleUser < ActiveRecord::Base
  include FluxxGrantRoleUser
end

app/models/sub_initiative.rb
class SubInitiative < ActiveRecord::Base
  include FluxxSubInitiative
end

app/models/sub_program.rb
class SubProgram < ActiveRecord::Base
  include FluxxSubProgram
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
  validates_confirmation_of :password
  acts_as_authentic do |c|
    # c.my_config_option = my_value # for available options see documentation in: Authlogic::ActsAsAuthentic
    c.act_like_restful_authentication = true
    c.validate_login_field=false
    c.validate_password_field=false
    c.validate_email_field=false
  end # block optional
  
  include ::FluxxGrantUser
  
  
  # TODO: Make it so that authlogic does not reindex delta indexing in sphinx upon signin
  
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  def to_key
     new_record? ? nil : [ self.send(self.class.primary_key) ]
  end
  
  private
  # NOTE ESH: Copied this method straight from authlogic's lib/authlogic/session/cookies.rb
  #           to force it to send the user_credentials cookie back with EVERY request.  This is an effort to prevent the session cookie
  #           or user_credentials cookie from being dropped
  # Tries to validate the session from information in the cookie
  def persist_by_cookie
    persistence_token, record_id = cookie_credentials
    if !persistence_token.nil?
      self.record = record_id.nil? ? search_for_record("find_by_persistence_token", persistence_token) : search_for_record("find_by_#{klass.primary_key}", record_id)
      self.unauthorized_record = record if record && record.persistence_token == persistence_token
      retval = valid?
      # Force the cookie to be sent back to the browser each time so it can be regained if it gets dropped
      save_cookie if retval && self.record
      retval
    else
      false
    end
  end
end

app/models/workflow_event.rb
class WorkflowEvent < ActiveRecord::Base
  include FluxxGrantWorkflowEvent
end

app/views/insta/_list_actions.html.haml
%li= link_to raw('&#9617;'), '#', :class => 'open-listing-actions', :title => 'Open/Close Listing Actions Tab'
%li= link_to image_tag('/images/fluxx_engine/theme/default/icons/page_white_excel.png', :alt => "Export to .xls"), url_for(:format => :xls), :class => 'area-data', :title =>'Export to .xls'
- if @first_report_id
  %li= link_to image_tag('/images/fluxx_engine/theme/default/icons/chart_bar.png', :alt => "Reports"), url_for(:fluxxreport_id => @first_report_id, :all_results => 1), :class => 'new-detail area-data', 'data-insert' => 'after', :title =>'Visualizations'
  %li= link_to image_tag('/images/fluxx_engine/theme/default/icons/arrow_join.png', :alt => "Conversion Funnel"), url_for(:view_funnel => 1, :all_results => 1), :class => 'new-detail area-data', 'data-insert' => 'after', :title =>'Conversion Funnel'
%li= link_to image_tag('/images/fluxx_engine/theme/default/icons/arrow_refresh.png', :alt => 'Refresh Card'), '#', :class => 'refresh-card', :title =>'Refresh Card'
%li= link_to image_tag('/images/fluxx_engine/theme/default/icons/cog_edit.png', :alt => 'Open Filters'), '#', :class => 'open-filters', :title =>'Filter Card'

app/views/insta/_show_action_buttons.html.haml
- reject_buttons = buttons.select {|button| event_name, english_event_name = button; english_event_name =~ /reject/i}
- send_back_buttons = buttons.select {|button| event_name, english_event_name = button; english_event_name =~ /send back/i}
- other_buttons = (buttons - reject_buttons) - send_back_buttons
- reordered_buttons =  reject_buttons + send_back_buttons + other_buttons
- reordered_buttons.each do |button_clause|
  - event_name, english_event_name = button_clause
  - english_event_name = model.event_to_english(event_name)
  - # There are a couple of special cases where action buttons should go to edit; one is for turning a request into a grant, the other is when marking a request transaction as paid; see below
  - if event_name.to_s =~ /become_grant/
    %li= link_to english_event_name, self.send("edit_#{@model_name}_path", {:approve_grant_details => event_name}), :class => 'to-self'
  - elsif event_name.to_s =~ /mark_paid/
    %li= link_to english_event_name, self.send("edit_#{@model_name}_path", :hidden_event_action => event_name), :class => 'to-self'
  - else
    %li= link_to english_event_name, self.send("#{@model_name}_path", {:event_action => event_name}), :class => 'as-put with-note', 'data-note-param'.to_sym => "#{@model_name}[workflow_note]"

app/views/insta/_show_extra_buttons.html.haml
- if model.is_a?(FipRequest) && model.granted?
  %li= link_to 'Add a Transaction', new_request_transaction_path(:request_transaction => {:request_id => model.id}), :title => 'Add A Transaction', :class => 'to-modal', :link_class => 'btn', 'data-on-success' => 'refreshCaller,close' if current_user.has_create_for_model?(RequestTransaction)

app/views/notes/_note_list.html.haml
- notable ||= nil
- unless notable
  - if params[:notable_id] && params[:notable_type]
    - notable = BlobStruct.new :id => params[:notable_id], :class => Kernel.const_get(params[:notable_type])
%table.tabular{:cellspacing => 0}
  - if notable
    %thead
      %tr
        %th
          = "Notes"
          %span.actions= link_to image_tag('/images/fluxx_engine/theme/default/icons/add.png', :class=> 'add-button'), new_note_path(:note => {:notable_id => notable.id, :notable_type => notable.class.name}), :class => 'to-modal', 'data-on-success' => 'refreshCaller,close', :title => "Add Note"
  %tbody
    - if !models || models.empty?
      %tr
        %td= "No Notes"
    - else
      - models.sort_by{|note| note.created_at ? (-1 * note.created_at.to_i) : Time.at(0).to_i }.each do |model|
        %tr
          %td
            - if model.respond_to? :note
              = model.note
            - else
              %strong
                = model.workflowable.class.state_to_english_translation model.old_state
                &#8594;
                = model.workflowable.class.state_to_english_translation model.new_state
              - unless model.comment.blank?
                <br/>
                = model.comment
            <br/>
            %span
              - if model.created_by
                By
                = model.created_by.full_name 
              - if model.created_at
                Added at
                = model.created_at.ampm_time
                on
                = model.created_at.full
              - else
                no timestamp
    %tr
      %td